export interface Line {
  id: string;
  elementId?: string;
  type: string;
  elementType: string;
  name?: string;
  src?: string;
  borderColor?: string;
  text?: string;
  width: number;
  height: number;
  groupId?: string | null;
  x: number;
  y: number;
  offsetX: number;
  offsetY: number;
  rotation: number;
  opacity: number;
  cropWidth: number;
  cropHeight: number;
  cropX: number;
  cropY: number;
  fontSize?: number | null;
  visible: boolean;
  padding: {
    paddingRight: boolean;
    paddingLeft: boolean;
    paddingTop: boolean;
    paddingBottom: boolean;
    horizontal: number;
    vertical: number;
  };
  fill: string;
  align: string;
  verticalAlign: string;
  fontStyle: string;
  letterSpacing: number;
  lineHeight: number;
  textTransform: string;
  textDecoration?: string;
  stroke: string;
  strokeWidth: number;
  points: number[];
  cornerRadius?: number | null;
  cornerRadiusTopLeft: number;
  cornerRadiusTopRight: number;
  cornerRadiusBottomLeft: number;
  cornerRadiusBottomRight: number;
  fontFamily: string;
  s3FilePath?: string;
  category?: string;
  paddingRatio: number;
  alpha: number;
  overlayFill: string;
  listening: boolean;
  index: number;
  scaleX: number;
  scaleY: number;
  fillPatternScaleX: number;
  fillPatternScaleY: number;
  svgElement?: any;
  imageWidth?: number | null;
  imageHeight?: number | null;
  mute: boolean;
  autoFitEnabled: boolean;
  shadowEnabled: boolean;
  shadowColor: string;
  shadowBlur: number;
  shadowOpacity: number;
  shadowOffsetX: number;
  shadowOffsetY: number;
  language?: string;
  radiusEnabled: boolean;
  enableWaterMark: boolean;
}
